/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: lampralexandros@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ArticleArticleImage from './ArticleArticleImage';

/**
 * The Article model module.
 * @module model/Article
 * @version 1.0.0
 */
class Article {
    /**
     * Constructs a new <code>Article</code>.
     * @alias module:model/Article
     * @param articleImage {module:model/ArticleArticleImage} 
     * @param articledate {Date} 
     * @param articletitle {String} 
     * @param articletext {String} 
     */
    constructor(articleImage, articledate, articletitle, articletext) { 
        
        Article.initialize(this, articleImage, articledate, articletitle, articletext);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, articleImage, articledate, articletitle, articletext) { 
        obj['articleImage'] = articleImage;
        obj['articledate'] = articledate;
        obj['articletitle'] = articletitle;
        obj['articletext'] = articletext;
    }

    /**
     * Constructs a <code>Article</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Article} obj Optional instance to populate.
     * @return {module:model/Article} The populated <code>Article</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Article();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('articleImage')) {
                obj['articleImage'] = ArticleArticleImage.constructFromObject(data['articleImage']);
            }
            if (data.hasOwnProperty('articledate')) {
                obj['articledate'] = ApiClient.convertToType(data['articledate'], 'Date');
            }
            if (data.hasOwnProperty('articletitle')) {
                obj['articletitle'] = ApiClient.convertToType(data['articletitle'], 'String');
            }
            if (data.hasOwnProperty('articletext')) {
                obj['articletext'] = ApiClient.convertToType(data['articletext'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
Article.prototype['_id'] = undefined;

/**
 * @member {module:model/ArticleArticleImage} articleImage
 */
Article.prototype['articleImage'] = undefined;

/**
 * @member {Date} articledate
 */
Article.prototype['articledate'] = undefined;

/**
 * @member {String} articletitle
 */
Article.prototype['articletitle'] = undefined;

/**
 * @member {String} articletext
 */
Article.prototype['articletext'] = undefined;






export default Article;

